### ISSUE TITLE
unable to connect to Nextcloud from Chrome

### ISSUE THREAD

**Issue by goldenscarab** [nextcloud/passman-webextension#319]
Hello,
when I set passman to connect to my Nextcloud, a javascript error is triggered and nothing happens
`framework.js:14327 Error: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at api_request (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/lib/api.js:193:28)
    at Object.getVaults (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/lib/api.js:18:13)
    at server (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/ui/popup/controllers/setup.js:81:26)
    at chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/ui/popup/controllers/setup.js:129:25
    at chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/vendor/angular/framework.js:19915:31
    at completeOutstandingRequest (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/vendor/angular/framework.js:6110:10)
    at chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/vendor/angular/framework.js:6389:7 Possibly unhandled rejection: {"stack":"Error: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.\n    at api_request (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/lib/api.js:193:28)\n    at Object.getVaults (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/lib/api.js:18:13)\n    at server (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/ui/popup/controllers/setup.js:81:26)\n    at chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/ui/popup/controllers/setup.js:129:25\n    at chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/vendor/angular/framework.js:19915:31\n    at completeOutstandingRequest (chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/vendor/angular/framework.js:6110:10)\n    at chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/js/vendor/angular/framework.js:6389:7"}`

**Comment by binsky08** [comment]
This project has been completely rewritten (v3).
The old code is archived in the `legacy-v2` branch.
Please check whether the issue still exists in the current v3, and if so, please report it again.
